name: D

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      uses: dlang-community/setup-dlang@v1

    - name: Install 32-bit toolchain and libraries
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install nasm:i386 make gcc-multilib g++-multilib git

    - name: 'Build'
      run: |
        dub --arch=x86 --build=release
